[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.default]
clear = true

[tasks.pusher]
command = "python3.8"
args = [ "src-py/mindustry-mods.py", "-ipd", "../" ]

# [task.runner]
# dependencies = [ "pusher" ]
# args = [ "-h" ]
